<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>9</LangVersion>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DefineConstants>$(DefineConstants);BADGE_DEBUG</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Svg" Version="3.4.7" />
		<PackageReference Include="System.Drawing.Common" Version="5.0.3" />
	</ItemGroup>

</Project>
