<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Configurations>Debug;Develop;Release</Configurations>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Nullable>disable</Nullable>
		<LangVersion>9</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DebugType>full</DebugType>
		<DefineConstants>$(DefineConstants);BADGE_DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
		<DebugType>pdbonly</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System.Drawing" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Svg" Version="3.4.4" />
	</ItemGroup>

</Project>
